package com.jufaja.inyedashares.models

data class DataPost (
    var aauser: User? = null,
    var abdate: Long = 0,
    var acpartyfunda: String = "",
    var adpartygrowa: String = "",
    var aepartyperca: String = "",
    var afpartyvaluea: String = "",
    var agpartyfundb: String = "",
    var ahpartygrowb: String = "",
    var aipartypercb: String = "",
    var ajpartyvalueb: String = "",
    var akpartyfundc: String = "",
    var alpartygrowc: String = "",
    var ampartypercc: String = "",
    var anpartyvaluec: String = "",
    var aopartyfundd: String = "",
    var appartygrowd: String = "",
    var aqpartypercd: String = "",
    var arpartyvalued: String = "",
    var astotalfunda: String = "",
    var atmultigrowa: String = "",
    var autotalgrowa: String = "",
    var avmultiperca: String = "",
    var awtotalperca: String = "",
    var axtotalfundb: String = "",
    var aymultigrowb: String = "",
    var aztotalgrowb: String = "",
    var bamultipercb: String = "",
    var bbtotalpercb: String = "",
    var bctotalfundc: String = "",
    var bdmultigrowc: String = "",
    var betotalgrowc: String = "",
    var bfmultipercc: String = "",
    var bgtotalpercc: String = "",
    var bhtotalfundd: String = "",
    var bimultigrowd: String = "",
    var bjtotalgrowd: String = "",
    var bkmultipercd: String = "",
    var bltotalpercd: String = "",
    var bmtotalabcd: String = "",
    var bnmultiprofi: String = "",
    var bototalprofi: String = "",
    var bppercentagex: String = "",
    var bqpercentagey: String = ""
)